### ISSUE TITLE
Adding Default parameters in server.conf

### ISSUE THREAD

**Issue by sudhanshu456** [awdeorio/mailmerge#102]
Adding a default will save the mailmerge from many errors while sending,
what we can add some default parameter inside a server.conf
like 

```
DEFAULT_MAIL=example@mail.com #mail id of the sender , so we don't need to worry one more parameter in the template.
DEFAULT_REPLY_TO=example@gmail.com # email id on which the reply mail will come
DEFAULT_TO_EMAIL = to email   #for checking test run, after that we don't need to specify our mail id.
```
using Default reply to will help many users because the email id from we sent our mail sometimes it doesn't accept reply back to that.
so it will be great to have some 'reply to' parameter which will allow a person to have a default reply back to the mail.

**Comment by awdeorio** [comment]
I'm a little nervous about things that appear "magical" from the perspective of the user.  For example, an email that lacks a `FROM` field which ends up being automatically filled in by mailmerge.
