### ISSUE TITLE
saving sent mails in a folder

### ISSUE THREAD

**Issue by sudhanshu456** [awdeorio/mailmerge#103]
Like we have Mozilla thunderbird client, which saves a local copy to sent mail.
This feature allows us to check back later how many and is the mail to that person is sent or not, many confirmations can be done by saving a local copy of mails.

It's easy to implement feature, we see output which mails is sent, during that it will place the same content from the output on the console in a text or HTML file. for each unique mails.

**Comment by sudhanshu456** [comment]
I'm working on it, now

**Comment by nickolay** [comment]
I posted a PR for this in https://github.com/awdeorio/mailmerge/pull/107

In addition to the logging use-case you mention, I needed this for template development (to open the message locally without having to send it). Also I'm hoping to use it to implement reliable e-mail delivery (https://github.com/awdeorio/mailmerge/issues/36), using mailmerge only as a .eml generator.

**Comment by awdeorio** [comment]
> I needed this for template development (to open the message locally without having to send it).

A quick work-around could be to use the `mailmerge --output-format raw` option and then split up the output with a quick script.

> Also I'm hoping to use it to implement reliable e-mail delivery (#36), using mailmerge only as a .eml generator.

I agree that reliable email delivery would be best implemented by starting with rendering all the templates into a folder.

In summary, I think that writing output to a folder is a niche use with a reasonable work-around.  I don't think it makes sense as a stand-alone feature.  I do think it makes sense as part of the bigger picture of reliable delivery #36.  I'm goingg to close this issue in favor of continuing the discussion under issue #36.
