### ISSUE TITLE
FEATURE MISSING: personal attachments

### ISSUE THREAD

**Issue by Cogitarian** [awdeorio/mailmerge#111]
Hi, 

I'd love to use this meilmerge instead of gmass or other clients. 
But I want to send different attachment for each recipient.

I thought the info about the attachment would be in the database file, 
not in the template file and reference to each attachment would be in 
{{}}, as all other alternating information in each email to be sent, right?

**Comment by seshrs** [comment]
Hi @Cogitarian,

You can specify a different attachment for each row in the database file if you wish. You'll just need to specify the right Jinja field in the template file under the "ATTACHMENT" header.

For instance, if this is your database`mailmerge_database.csv` (where the `attachment` column holds the file path):
```
email,name,attachment
myself@mydomain.com,"Myself","myself.pdf"
bob@bobdomain.com,"Bob","bob.pdf"
```

Then you ccould modify your template `mailmerge_template.txt` as follows:
```
TO: {{email}}
SUBJECT: Testing mailmerge
FROM: My Self <myself@mydomain.com>
ATTACHMENT: {{attachment}}

Hi, {{name}}.
```

Feel free to follow up if I misunderstood your question 😃

**Comment by Cogitarian** [comment]
You are right and this is exactly what I was looking for! Thanks a lot!
