### ISSUE TITLE
Apple Mail with attachments issue (former title: UTF-8 support issue)

### ISSUE THREAD

**Issue by lustasag** [awdeorio/mailmerge#113]
I have tried sending PDFs (diplomas) to participants of an event, and I've used UTF-8 in file names as well as in the body of the text. The result was pretty mixed: some mail clients displayed only the text, others just the attachment. 

How stable is UTF-8 support by mailmerge? Would it be possible for example to control if its base64 or quoted printable etc.?

I don't know much about MIME and it's quite painful to debug mailmerge in a 'production' situation... But it looks like a very easy to use and versatile tool that would be very useful to me :-)

**Comment by awdeorio** [comment]
Could you provide a simplified example so that I can take a deeper look?  A single database row with a very small template and a sample attachment file with the filename that causes a problem.

**Comment by seshrs** [comment]
Also, what mail clients showed only the text or only the attachment? (I’ve only ever tested Mailmerge with Gmail 😅)

---

Regarding current UTF-8 support: Attachments are base-64 encoded, and the encoding of the text part is set to UTF-8 if we detect any non-ASCII character:

https://github.com/awdeorio/mailmerge/blob/35a4b7176061883a30d5b05cfd10bfe4dd629989/mailmerge/template_message.py#L80

**Comment by lustasag** [comment]
The database, say, looked like this:
`name,email`
`Širbág Lérua,address@someprovider`

The template that failed was like this
`TO: {{email}}`
`SUBJECT: QBronze52 quantum programming workshop diploma`
`FROM: QCzech <qczech@qworld.xx.lv>`
`ATTACHMENT: ../diplomas/QBronze52_{{name}}.pdf`
` `
`Hello,`
` `
`We were very happy to see you at our workshop, and are sending you your well-deserved diploma. You did well at the workshop, congratulations!`
` `
`Best regards,`
` Aurél and Daniel`

What happened is that mailmerge seemed to collect everything fine. The body text was base64 encoded, the attachment was seen in raw mode. However, people with "Thunderbird" saw only the text body, while "MacOS Mail" displayed only the attachment.

Then I added this to the template:
`Content-Type: multipart/mixed; boundary="qbronze52boundary=6954384027655591914"`
` `
`--qbronze52boundary=6954384027655591914`
`Content-Type: text/plain; charset="UTF-8"`
`Content-Transfer-Encoding: quoted-printable`
Plus a closing boundary and quoted the accented 'é' character

And the weirdest thing that happened is that 'mailmerge' worked fine on people with UTF-8 in their names, but bailed out with an error on us-ascii names (note that the name appeared only in the file name, not in the message body or header). So I took out the accented character and with that the e-mails seems to be opening correctly on everyone's mail client. Perhaps this would have fixed also the first problem...

**Comment by lustasag** [comment]
mailmerge uses Python 3.8.2 from Anaconda.

Here's my raw output. The charset in the MIME part header seems to be different than for you.

```
Content-Type: multipart/alternative;
 boundary="===============4544315769929913869=="
MIME-Version: 1.0
SUBJECT: QBronze52 quantum programming workshop diploma
TO: xx@xxx.cz
FROM: QCzech <qczech@qworld.xx.lv>
Date: Thu, 25 Feb 2021 10:52:36 -0000

--===============4544315769929913869==
MIME-Version: 1.0
Content-Type: text/mixed; charset="none"
Content-Transfer-Encoding: base64

SGVsbG8sCgpXZSB3ZXJlIHZlcnkgaGFwcHkgdG8gc2VlIHlvdSBhdCBvdXIgd29ya3Nob3AsIGFu
ZCBhcmUgc2VuZGluZyB5b3UgeW91ciB3ZWxsLWRlc2VydmVkIGRpcGxvbWEuIFlvdSBkaWQgd2Vs
bCBhdCB0aGUgd29ya3Nob3AsIGNvbmdyYXR1bGF0aW9ucyEKCkJlc3QgcmVnYXJkcywKIEF1culs
IGFuZCBEYW5pZWwK

--===============4544315769929913869==
Content-Type: application/octet-stream;
 Name*=utf-8''QBronze52_%C5%A0irb%C3%A1g%20L%C3%A9rua.pdf
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: =?utf-8?b?YXR0YWNobWVudDsgZmlsZW5hbWU9IlFCcm9uemU1Ml8=?=
 =?utf-8?b?xaBpcmLDoWcgTMOpcnVhLnBkZiI=?=

c2VtbWkK

--===============4544315769929913869==--
>>> message 1 sent
>>> Limit was 1 message.  To remove the limit, use the --no-limit option.
>>> This was a dry run.  To send messages, use the --no-dry-run option.
```

**Comment by awdeorio** [comment]
Thanks for being patient and helping to debug this issue.  The `Content-Type: text/mixed; charset="none"` could be related to the problem, although I'm not 100% sure.  Could you try removing the `ATTACHMENT` header and show me the raw output?  I want to see if the `Content-Type` is still wrong even without the attachment.

**Comment by lustasag** [comment]
Oops, I have to apologise twice. In the previous output I have accidentally left the line
```
Content-Type: multipart/mixed; boundary="qbronze52boundary=6954384027655591914"
```
When that's not there, my output is the same as yours (us-ascii or utf-8, depending on the template text).

The second apologies go for not testing enough. Actually, it seems UTF-8 may not make a difference finally, and simply the message constructed by mailmerge displays incorrectly in Apple's mail. All I see is an empty message with a "icon" for the attachment. I don't have Thunderbird installed so I can't test it, but the addressees reported that they saw only the text, but no sign of the attachment. One has looked at the raw message and the attachment was indeed part of it, and the same hold for my inbox, when look at the raw, or use Exchange or the webmail interface the attachment is there and is visible, respectively.

**Comment by awdeorio** [comment]
At this point, I'm a bit confused about what's going on.  Could you post a complete corrected simple database, simple template message using the "triple back tics", and exact raw output?  I want to make sure I got this right.

Next, could you send yourself the simple template message and open your own message in Apple mail?  Let me know what you see.  The reason I'm asking is that we need to be able to reproduce the problem in order to fix it.

**Comment by lustasag** [comment]
OK, sorry for the mess.

Here's a database:
```
name,email
Sirbag Lerua,address@someprovider
```
and a template:
```
TO: {{email}}
SUBJECT: QBronze52 quantum programming workshop diploma
FROM: QCzech <qczech@qworld.xx.lv>
ATTACHMENT: QBronze52_{{name}}.pdf

Hello,

We were very happy to see you at our workshop, and are sending you your well-deserved diploma. You did well at the workshop, congratulations!
```

The output ```mailmerge --output-format raw``` gives me is
```
Content-Type: multipart/alternative;
 boundary="===============7623278080483302674=="
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
TO: address@someprovider
FROM: QCzech <qczech@qworld.xx.lv>
SUBJECT: QBronze52 quantum programming workshop diploma
Date: Mon, 01 Mar 2021 20:35:01 -0000

--===============7623278080483302674==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello,

We were very happy to see you at our workshop, and are sending you your well-deserved diploma. You did well at the workshop, congratulations!

Best regards,
 Aurel and Daniel

--===============7623278080483302674==
Content-Type: application/octet-stream; Name="QBronze52_Sirbag Lerua.pdf"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="QBronze52_Sirbag Lerua.pdf"

c2VtbWkK

--===============7623278080483302674==--
```

Here's a screenshot of what Apple Mail shows me: https://we.tl/t-whQq7x1cnJ 
It's an empty message with only a single attachment. Opening the same e-mail on OWA webmail, works just fine. Moreover, when I select "View->Message->Raw source" in the Apple Mail client, I see the exact same content that mailmerge generated with the ```--raw``` option so it's not simply a matter of the message getting distorted on the way.

**Then I hacked this template**
```
TO: {{email}}
SUBJECT: QBronze52 quantum programming workshop diploma
FROM: QCzech <qczech@qworld.xx.lv>
ATTACHMENT: QBronze52_{{name}}.pdf
Content-Type: multipart/mixed; boundary="qbronze52boundary=6954384027655591914"

--qbronze52boundary=6954384027655591914
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
Hello,

We were very happy to see you at our workshop, and are sending you your well-deserved diploma. You did well at the workshop, congratulations!

Best regards,
 Aurel and Daniel

--qbronze52boundary=6954384027655591914
```

Which already produced the desired output in Apple Mail, as well as the participants with Thunderbird were also happy finally :) This issue with this hack was that it worked only if the message body was not UTF-8, this is what confused me into thinking that the whole problem had something to do with UTF-8.

**Comment by awdeorio** [comment]
Thanks for the nice clear summary @lustasag , that's really helpful.  It looks like the root cause of the problem is the 
`Content-Type: multipart/alternative` vs. `Content-Type: multipart/mixed` headers.  @seshrs was the original author the attachments feature, so I'll see if he has any insights.

**Comment by seshrs** [comment]
Thanks @lustasag and @awdeorio! Yes, looks like we’re using `multipart/alternative` incorrectly (based on the answers in https://stackoverflow.com/a/23853079). I’ll experiment with this soon 😃
