### ISSUE TITLE
mails limit per mail feature

### ISSUE THREAD

**Issue by horllste** [awdeorio/mailmerge#126]
please how do i use the mail send limit per minute added in this PR
#114 

i tried
mailmerge --no-dry-run --no-limit --rate 20
and i got error
thanks

**Comment by awdeorio** [comment]
I haven't yet created a release with that feature.  Try grabbing the latest `develop`.  Then, `mailmerge --sample`.  Take a look at the configuration in the sample `mailmerge_server.conf`.  Let me know if you need more pointers.

**Comment by horllste** [comment]
thanks, i will check that

**Comment by horllste** [comment]
> thanks, i will check that

there is no changes in the mailmerge_server.conf, please i still need more pointers.

**Comment by awdeorio** [comment]
I just did a new [release](https://github.com/awdeorio/mailmerge/releases/tag/2.2.0) with the latest features.  Try installing that globally with:

```console
$ pip install --upgrade mailmerge
$ mailmerge --version
mailmerge, version 2.2.0
```

**Comment by horllste** [comment]
okay, thanks, i have seen the changes, i ill test it and comment back here later as soon as i test it.
thanks
