### ISSUE TITLE
HTML based e-mail template

### ISSUE THREAD

**Issue by hawaltie** [awdeorio/mailmerge#14]
I Don know is this is the right way, but I want to know whether it is possible to use an html based mail als template.

**Comment by awdeorio** [comment]
Yes, HTML email templates work out-of-the-box.

**Comment by hawaltie** [comment]
Thank you for the quick response. Do you know where can I find an example
of a html template for this application?

Regards,

Hans.

Op 30 apr. 2017 14:55 schreef "Andrew DeOrio" <notifications@github.com>:

**Comment by awdeorio** [comment]
I added an example to the README: https://github.com/awdeorio/mailmerge#html-formatting-example

**Comment by hawaltie** [comment]
Thanks! I missed the  Content-Type: text/html part in my message.

Regards,

Hans.

Op 1 mei 2017 14:02 schreef "Andrew DeOrio" <notifications@github.com>:

I added an example to the README: https://github.com/awdeorio/
mailmerge#html-formatting-example

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/awdeorio/mailmerge/issues/14#issuecomment-298324010>,
or mute the thread
