### ISSUE TITLE
New release on Pipy

### ISSUE THREAD

**Issue by taupezen** [awdeorio/mailmerge#151]
Hi,

Thanks for this tool. I initially pulled it from pipy ; while encountering problems with Excell (in my locale, it uses automatically ";" as you already know it), i figured that the release on pipy in behing thoses changes. 

Of course i managed myself to install from the repo, but shouldn't be a new release at least with the bom detection, and the excell dialect probing included, and published on pipy. These are great additions and are not reflected on the pipy public version, main entrance for python package. Maybe it's time for a 2.2.2 release with pipy ?

This is -- of course -- just a suggestion.
Best regards.

**Comment by awdeorio** [comment]
Thanks for the reminder!  This is done https://github.com/awdeorio/mailmerge/releases/tag/2.2.2

```console
$ pip install --upgrade mailmerge
$ mailmerge --version
mailmerge, version 2.2.2
```
