### ISSUE TITLE
No mailmerge_server.conf file in the repository

### ISSUE THREAD

**Issue by robstewart57** [awdeorio/mailmerge#153]
The `README.md` file says:

> Other configuration examples are in the comments of mailmerge_server.conf

However there isn't a `mailmerge_server.conf` file in the repository.

The server configuration examples are currently in `create_sample_input_files` in `__main__.py` https://github.com/awdeorio/mailmerge/blob/develop/mailmerge/__main__.py#L183

**Comment by awdeorio** [comment]
The current method to get a set a sample files is `mailmerge --sample`, which writes the files to the present working directory.  Another way to do it would be for the `mailmerge --sample` to *copy* sample files from the package install directory to the PWD.

I assume that you're thinking it would be useful to be able to read that config file without needing to use the tool to generate a file.  Or maybe I'm missing something.  A little more context would help.

**Comment by robstewart57** [comment]
> The current method to get a set a sample files is mailmerge --sample

My bad, I completely missed this @awdeorio .

> I assume that you're thinking it would be useful to be able to read that config file without needing to use the tool to generate a

Perhaps very marginally it would be useful to have a `mailmerge_server.conf` file in the repository without needing to run `mailmerge --sample`, e.g. if a user was using the GitLab website as a tutorial. However, that file would need to be versioned with every change to `create_sample_input_files`, creating duplication.

I'll close this issue.
