### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by bexelbie** [awdeorio/mailmerge#20]
It'd be nice to be able to include attachments

**Comment by awdeorio** [comment]
Great idea!  Any suggestions on how to specify the attachments in a template template email?  Do you know if native sendmail format (the template is based on that) has support for attachments that I could mimic?

**Comment by bexelbie** [comment]
I do not know if sendmail supports them.  I suspect they will need to be encoded/built.  This link seems to indicate it isn't that challenging: https://stackoverflow.com/questions/3362600/how-to-send-email-attachments

As for inclusion, can we add an `Attachments: ` at the top after To, From, etc.?

**Comment by awdeorio** [comment]
I suppose that adding an`Attachments:` header could work.  On the up side, you could specify a filename using jinja templates.  On the down side, it would diverge from the standard email format that is universal, e.g., works with `sendmail`.

Another approach could be a command line switch to `mailmerge`.  For example, `mailmerge --attachment photo.jpg`.  However, a weakness to this approach would be that you couldn't include a different attachment for different email addresses using the template.

**Comment by awdeorio** [comment]
Closed by PR #32 thanks to @seshrs
