### ISSUE TITLE
Not sending to multiple recepients

### ISSUE THREAD

**Issue by hawaltie** [awdeorio/mailmerge#21]
I have tried to use this script to send one mail message to mulitple recepients, but it did't work out. I have tried the following syntaxes:

email, name
"johndoe1@test.com,johndoe2@test.com", "John Doe"
"johndoe1@test.com, johndoe2@test.com", "John Doe"
"johndoe1@test.com;johndoe2@test.com", "John Doe"
"johndoe1@test.com; johndoe2@test.com", "John Doe"
johndoe1@test.com; johndoe2@test.com, "John Doe"

Bot none of them seem to work.

**Comment by awdeorio** [comment]
Try comma separated email addresses.  This template works for me:

```
TO: {{email1}}, {{email2}}
SUBJECT: Testing mailmerge
FROM: My Self <myself@mydomain.com>

Hello world!
```

**Comment by hawaltie** [comment]
Thanks!  I'll try
