### ISSUE TITLE
HTML and Plain text

### ISSUE THREAD

**Issue by nicwells** [awdeorio/mailmerge#23]
Is there a way to provide both an HTML and a plain text template? Thanks!

**Comment by wellseee** [comment]
I can see how you can do this now. You need to specify as MIME formatted message in the template by specifying a MIME field and following the standard email message format(s). Something along these lines in case anyone else is wanting to do similar.

TO: {{email}}
SUBJECT: Testing mailmerge
FROM: My Self <myself@mydomain.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="outer-boundary"

This is a MIME-encoded message. If you are seeing this, your mail
reader is old.
--outer-boundary
Content-Type: text/plain; charset=us-ascii

This message might make you :) or it might make you :(

--outer-boundary
MIME-Version: 1.0
Content-Type: multipart/related;
  type="text/html"; start="<body@here>"; boundary="inner-boundary"

--inner-boundary
Content-Type: text/html; charset=us-ascii
Content-Disposition: inline
Content-ID: <body@here>

<html>
 <body>
  This message might make you
  <em>Shout</em>
  or it might make you<bold>Scream</bold>
 </body>
</html>

--outer-boundary--

**Comment by awdeorio** [comment]
Thanks for the example!  I'll add this to the README.

**Comment by nicwells** [comment]
@awdeorio no problem. Thanks so much for making this tool, it's great. I was just about to look into implementing utf/character encoding support but looks like you may have just done that so that is fantastic!
