### ISSUE TITLE
Missing date in header

### ISSUE THREAD

**Issue by Rasmis** [awdeorio/mailmerge#28]
I am having trouble using mailmerge, because it does not set a date-header. That causes X-Amavis / amavisd to block it as spam. Here are the two types of error I get:

    The message WAS NOT relayed to:
    <-receiver->:
    554 5.6.0 Bounce, id=23674-07 - BAD HEADER

    This nondelivery report was generated by the program amavisd-new at host
    -receiver-. Our internal reference code for your message is
    23674-07/WzRLAsDqSAcp
    
    INVALID HEADER
    
    Missing required header field: "Date"

And

    X-Virus-Scanned: amavisd-new at server3533.serverpark.dk
    X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"

**Comment by awdeorio** [comment]
Thanks for creating to issue!  I think it should be fairly straight forward to add a header.  The `parsemail()` method might be a good place.  https://github.com/awdeorio/mailmerge/blob/develop/mailmerge/api.py#L30  Send a PR my way and we'll get it merged!

**Comment by awdeorio** [comment]
Closed by #29
