### ISSUE TITLE
Problem with body of email

### ISSUE THREAD

**Issue by llenlewag** [awdeorio/mailmerge#48]
Hi,
I want to use mailmerge cause you made a great job. But I have a problem with the body of the template. Instead of : 

`ATTACHMENT: classes/{{classe}}.xls

Bonjour {{name}},

En tant que PP de la classe de {{classe}}, je t'envoie la liste des codes rÃ©seau de tes eleves. 
C'est ce code qu'ils utilisent pour ouvrir une session sur les ordinateurs du lycee. 
A toi de les distribuer s'ils ne les ont pas deja.

Cordialement,

`
I have : 

`ATTACHMENT: classes/2_A.xls
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Date: Sat, 31 Aug 2019 15:32:22 -0000

Qm9uam91ciBNaWNoZWwsCgpFbiB0YW50IHF1ZSBQUCBkZSBsYSBjbGFzc2UgZGUgMl9BLCBqZSB0
J2Vudm9pZSBsYSBsaXN0ZSBkZXMgY29kZXMgcsODwqlzZWF1IGRlIHRlcyBlbGV2ZXMuIApDJ2Vz
dCBjZSBjb2RlIHF1J2lscyB1dGlsaXNlbnQgcG91ciBvdXZyaXIgdW5lIHNlc3Npb24gc3VyIGxl
cyBvcmRpbmF0ZXVycyBkdSBseWNlZS4gCkEgdG9pIGRlIGxlcyBkaXN0cmlidWVyIHMnaWxzIG5l
IGxlcyBvbnQgcGFzIGRlamEuCgpDb3JkaWFsZW1lbnQsCgotLSAKTWljaGVsIFZpZW5uZQpBQyAv
IElTTiAvIE5TSSAvIFNJTwpSZWZlcmVudCBudW1lcmlxdWUKTFBPIEJsYWlzZSBQYXNjYWwK
attached /home/vienne/Documents/reseau/classes/2_A.xls
sent message 0 DRY RUN
`
I have been looking but not finding. Do you have any idea? Am I dumb ?

**Comment by awdeorio** [comment]
Mailmerge automatically adds some email headers, like these:
```
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Date: Sat, 31 Aug 2019 15:32:22 -0000
```

They are OK to leave in the email.  Did I miss part of your question?

**Comment by llenlewag** [comment]
They are in the email created. I just don't put it to reduce my post.

vienne@gargantua:~/Documents/reseau$ mailmerge --dry-run --limit 1
>>> encoding utf-8
>>> message 0
TO: me@mydomain.com
SUBJECT: Je teste mailmerge
FROM: Me<myaddress@me.com>
ATTACHMENT: classes/2_A.xls
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Date: Sat, 31 Aug 2019 15:32:22 -0000

Qm9uam91ciBNaWNoZWwsCgpFbiB0YW50IHF1ZSBQUCBkZSBsYSBjbGFzc2UgZGUgMl9BLCBqZSB0
J2Vudm9pZSBsYSBsaXN0ZSBkZXMgY29kZXMgcsODwqlzZWF1IGRlIHRlcyBlbGV2ZXMuIApDJ2Vz
dCBjZSBjb2RlIHF1J2lscyB1dGlsaXNlbnQgcG91ciBvdXZyaXIgdW5lIHNlc3Npb24gc3VyIGxl
cyBvcmRpbmF0ZXVycyBkdSBseWNlZS4gCkEgdG9pIGRlIGxlcyBkaXN0cmlidWVyIHMnaWxzIG5l
IGxlcyBvbnQgcGFzIGRlamEuCgpDb3JkaWFsZW1lbnQsCgotLSAKTWljaGVsIFZpZW5uZQpBQyAv
IElTTiAvIE5TSSAvIFNJTwpSZWZlcmVudCBudW1lcmlxdWUKTFBPIEJsYWlzZSBQYXNjYWwK

>>> attached /home/me/Documents/reseau/classes/2_A.xls
>>> sent message 0 DRY RUN
>>> Limit was 1 messages.  To remove the limit, use the --no-limit option.
>>> This was a dry run.  To send messages, use the --no-dry-run option.

**Comment by bexelbie** [comment]
@llenlewag the email has been base64 encoded because of the accented characters.  If you use something like https://www.base64decode.org you can verify the text

**Comment by llenlewag** [comment]
Ok. Thx So I need to change something to have my real text in the email? I tested to send it and I receive the text in base 64 but I'm sure that my workmates will decode it.

**Comment by bexelbie** [comment]
@llenlewag no changes should be needed. You are writing in French which includes characters not in the base ascii set.  These characters get encoded for transmission because the email transmission standards pre-date allowing "special" characters.  Base64 is one of those encodings.  (This is the short story, it is more nuanced).

Send yourself a test email with the --no-dry-run option and with your address as the first one in your database.  You should see the text exactly as expected, en Francais.  Almost all mail readers in use today will automatically decode these messages for display.  Anyone using one that doesn't is almost certainly choosing that on purpose and has an alternative rendering system set up.
