### ISSUE TITLE
Inline image from attachment

### ISSUE THREAD

**Issue by captn3m0** [awdeorio/mailmerge#86]
I was wondering if something like this would be possible:

```
ATTACHMENT: u4qSjQL.jpeg
![](u4qSjQL.jpeg)
```

I tried it, and it renders to just an image tag: `<p><img alt="" src="u4qSjQL.jpeg" /></p></body></html>`

Apparently, it is possible via a [href that points to the `cid`](https://stackoverflow.com/a/41994121).

**Comment by awdeorio** [comment]
This is a great idea.  Here's a [Python example](https://stackoverflow.com/questions/920910/sending-multipart-html-emails-which-contain-embedded-images).

I think that the only modifications needed would be:
1. When attaching an image, add a header `Content-ID: <filename>`
2. Add an example to the README with an HTML email containing an image `<img src="cid:<filename>"

**Comment by seshrs** [comment]
> When attaching an image, add a header Content-ID: <filename>

While this will work for most use cases, we’d have to be careful about attachments from different paths with the same filename. (Then they’d all get the same content ID!)

To fix this, we may have to transform all occurrences of a given attachment path to a randomly generated content ID. (With this approach, the message template would specify inline images as `<img src=“./path/to/img.jpg” />`, and the path would be mapped to the correct content ID.)

**Comment by captn3m0** [comment]
I'm going to take a stab at this, thanks for the pointers.

Will report back if I face issues.

**Comment by captn3m0** [comment]
Have a question regarding the implementation of the transformation.

I was thinking of writing the transformation as a [markdown extension](https://python-markdown.github.io/reference/#markdown), which would work wonderfully, but won't work for the HTML email usecase.

To cover the HTML usecase, I would have to rewrite it with a html-parser (need suggestions here, do we want a heavy dependency like beautifulsoup?) and that kinda makes the markdown extension redundant. 

3 options:

- [ ] Keep the feature markdown-only (easy implementation, no extra dependencies)
- [ ] Implement it twice, once as a markdown extension, and once for direct HTML emails.
- [ ] Implement it once, just for HTML, and run the output of the markdown against the HTML transform.

Or is there an easy way to do HTML parsing natively in Python?

**Comment by awdeorio** [comment]
Hmm, it sounds like the reason for the markdown extension and the reason for possible HTML parsing is handling the "two attachments with same basename" case.  The problem is the name clash in `Content-Id`, which is the basename of the two attachments.

How about making the `Content-Id` value the same as the user-specified attachment path?  For example, a markdown formatted email with two attachments could look like this:

```eml
To: to@test.com
Attachment: dog.jpg
Attachment: ../dog.jpg
Content-Type: text/markdown

Dog 1 ![dog 1](cid:dog.jpg)

Dog 2 ![dog 2](cid:../dog.jpg)
```

The same message formatted with plaintext and HTML would be like this:
```eml
To: to@test.com
Content-Type: multipart/alternative; boundary="boundary"
MIME-Version: 1.0
Attachment: dog.jpg
Attachment: ../dog.jpg

--boundary
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Plaintext dog 1 and dog 2.

--boundary
Content-Type: text/html; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<html><body>
<p><img alt="dog 1" src="cid:dog.jpg" /></p>
<p><img alt="dog 2" src="cid:../dog.jpg" /></p>
</body></html>
```

**Comment by captn3m0** [comment]
- Didn't think of letting the user control CID, but it makes sense.
- I am not 100% sure if all valid paths (*nix,windows) will also remain valid CIDs. Will check on this and get back :+1:

**Comment by captn3m0** [comment]
The spec says that cids must match the `addr-spec`, so they must match a valid email address. (Looks like all the SO answers don't match the spec).

Python 3.2+ comes with a cool `email.utils.make_msgid` method:

https://github.com/python/cpython/blob/68b352a6982f51e19bf9b9f4ae61b34f5864d131/Lib/email/utils.py#L174-L194

which adds a bit more randomness (and leaks the hostname). But that would still require html parsing to replace hrefs.

Going to pick https://pypi.org/project/html5/, which looks okay-enough for our usecase, and has zero-dependencies.

**Comment by captn3m0** [comment]
Got html5lib to working, but facing interesting test breakages because the markdown->html and markdown->html->html results in different orderings.

```
- <img alt="python logo not attached" src="http://pluspng.com/img-png/python-logo-png-open-2000.png" /></p></body></html>
+ <img src="http://pluspng.com/img-png/python-logo-png-open-2000.png" alt="python logo not attached" /></p></body></html>
```
