### ISSUE TITLE
Rate limiting option

### ISSUE THREAD

**Issue by bexelbie** [awdeorio/mailmerge#92]
Is there interest in a flood limit timer? For example, my ISP has a limit of 50 emails in 5 minutes.  I'd love to be able to tell mailmerge this so i can just leave a process running.  Perhaps something like:

mailmerge ... --pause-count=50 --pause-time=600

--pause-count = Pause after this many emails are sent - default 0
--pause-time = Pause for this long in seconds - default 0

Error condition if either is set to a negative value or if only one is set to a positive value

WDYT?

**Comment by awdeorio** [comment]
I like this idea!  Do you think a single option like `--limit-rate=10` expressed in emails per minute would work for most users?  That might be more simple for the end user.  Email could be sent spaced evenly every `1/RATE_LIMIT` minutes.  Loosely inspired by `wget`.

Another single-option possibility might be `--wait=6`.  Wait 6 seconds between emails.  Also inspired by `wget`.

**Comment by bexelbie** [comment]
I prefer `--limit-rate=10` with that being number of emails per minute, assuming we define rounding (I'd round down) and sleep for that many (micro)seconds between each mail.  I'd like anything that doesn't require users to do math :D

**Comment by awdeorio** [comment]
I like `--limit-rate=10`.

I'm thinking that math should round up, possibly to the nearest second.  Here's an example.  Let's say a server has a limit of 7 messages per second.  60/7 = 8571.429 ms between messages = 8571 after rounding down.  The first message will be sent at t=0, and the 8th message will be sent at t=159997 ms = 59.997 s.  This could trigger the server's message limit.

Also, a UI idea: perhaps printing a `.` every 1 s while waiting might be nice.  Maybe something like `Waiting 8 seconds for rate limit .......`.

**Comment by bexelbie** [comment]
Sounds good.  I was actually thinking round up and wrote round down anyway :D

While I wouldn't mind working on this, if anyone is watching and wants it - take it.  I have limited time.

**Comment by awdeorio** [comment]
Shower thought: a rate limit a property of a server.  Perhaps the best place to specify the rate limit would be in `mailmerge_server.conf`.  Of course, it would be fine to have a command line option to override the config file limit.

**Comment by bexelbie** [comment]
I like this idea and it feels logical.  I don't know if we really need an override switch ... unless we want to start letting more stuff be overriden.

One of my use cases would be to override the username for some emails.  Do you want to go down this road?

**Comment by awdeorio** [comment]
> One of my use cases would be to override the username for some emails. Do you want to go down this road?

My preference would be for a clean separation of content (`template.txt`) and server configuration (`server.conf`).

**Comment by bexelbie** [comment]
> My preference would be for a clean separation of content (`template.txt`) and server configuration (`server.conf`).

Agreed.  I was suggesting that if we allow the override of the limit field in `server.conf` should we allow it for other fields?  If so, we may want to design a switch setup that groups this.

**Comment by awdeorio** [comment]
> Agreed. I was suggesting that if we allow the override of the limit field in server.conf should we allow it for other fields? If so, we may want to design a switch setup that groups this.

Ah, now I understand, seems reasonable.  I think that for the purpose of this issue, keeping it simple would be good.  I like the idea of adding a server config parameter that controls the limit rate.

**Comment by sudhanshu456** [comment]
Please implement that idea , I started using your mailmerge python lib but the error was my SMTP server allow 14 mails/sec but due to high speed to internet connection sending rate is much higher than that, so many people didn't get the mails.

**Comment by bexelbie** [comment]
@sudhanshu456 please submit your PR :) I am backed up and am not trying to "lick this cookie"

**Comment by MrSeccubus** [comment]
Should be fixed in PR #114 now. But with a minute resolution, not a second resolution.
