### ISSUE TITLE
With attachments its send duplicate header of Content Type

### ISSUE THREAD

**Issue by asadbd07** [awdeorio/mailmerge#94]
This is the email header with attachment . Without attachment is okay

> Content-Type: multipart/alternative; boundary="===============6399458286909476=="
> MIME-Version: 1.0
> Content-Type: multipart/alternative; boundary="===============6399458286909476=="
> SUBJECT: Testing mailmerge
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
> FROM: User <email@email.com>
> TO: noreply@user.com
> Date: Mon, 18 May 2020 18:21:03 -0000

**Comment by asadbd07** [comment]
I solved it by adding these
`        del self._message['Content-Type']`
`        del self._message['MIME-Version']`

after line 104 at template_message.py

For duplicate header keys my mail was bouncing.

Thanks

**Comment by seshrs** [comment]
@asadbd07 that's interesting, I also see the duplicate headers when dry-running with any attachment template. I think this issue should be fixed.

However, it seems like Gmail (and [another email parser I found online](https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx)) parse the email and show the email+attachment correctly. I'm curious, which mail client did you experience the issue in?

**Comment by seshrs** [comment]
@asadbd07 Do you want to take a stab at fixing this?

**Comment by asadbd07** [comment]
@seshrs I tried Zimbra, Roundcube, Gmail same problem then i decided to use 
`del self._message['Content-Type']`
`del self._message['MIME-Version']`

Then its worked fine for me :)

**Comment by seshrs** [comment]
Awesome!

> @asadbd07 Do you want to take a stab at fixing this?

What I meant was: Would you like to [open a Pull Request](http://makeapullrequest.com/) to this repository with your proposed fix? (Looks like it could make for a great first-time contribution, especially since you already have explored the code 😃 )

**Comment by asadbd07** [comment]
No thank you :)
